apiVersion: v1
kind: Service
metadata:
  name: {{ include "activity-hub.fullname" . }}-api
  labels:
    {{- include "activity-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "activity-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
